"""Initial migration

Revision ID: 3eaa6a7a367b
Revises: 
Create Date: 2025-12-29 23:19:27.998719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '3eaa6a7a367b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: pgvector extension must be created by a superuser before running this migration:
    # CREATE EXTENSION IF NOT EXISTS vector;
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reg_doc',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('parent_code', sa.String(length=50), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('sort_key', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reg_doc_code'), 'reg_doc', ['code'], unique=False)
    op.create_index('ix_reg_doc_language_code', 'reg_doc', ['language', 'code'], unique=True)
    op.create_index(op.f('ix_reg_doc_parent_code'), 'reg_doc', ['parent_code'], unique=False)
    op.create_table('reg_doc_chunk',
    sa.Column('reg_doc_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reg_doc_id'], ['reg_doc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reg_doc_chunk_content_tsv', 'reg_doc_chunk', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_reg_doc_chunk_doc_ordinal', 'reg_doc_chunk', ['reg_doc_id', 'ordinal'], unique=True)
    op.create_index(op.f('ix_reg_doc_chunk_reg_doc_id'), 'reg_doc_chunk', ['reg_doc_id'], unique=False)
    op.create_table('reg_doc_event',
    sa.Column('reg_doc_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('rg_no', sa.String(length=20), nullable=True),
    sa.Column('ek', sa.String(length=20), nullable=True),
    sa.Column('ae_no', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reg_doc_id'], ['reg_doc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reg_doc_event_doc_id', 'reg_doc_event', ['reg_doc_id'], unique=False)
    op.create_index(op.f('ix_reg_doc_event_reg_doc_id'), 'reg_doc_event', ['reg_doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reg_doc_event_reg_doc_id'), table_name='reg_doc_event')
    op.drop_index('ix_reg_doc_event_doc_id', table_name='reg_doc_event')
    op.drop_table('reg_doc_event')
    op.drop_index(op.f('ix_reg_doc_chunk_reg_doc_id'), table_name='reg_doc_chunk')
    op.drop_index('ix_reg_doc_chunk_doc_ordinal', table_name='reg_doc_chunk')
    op.drop_index('ix_reg_doc_chunk_content_tsv', table_name='reg_doc_chunk', postgresql_using='gin')
    op.drop_table('reg_doc_chunk')
    op.drop_index(op.f('ix_reg_doc_parent_code'), table_name='reg_doc')
    op.drop_index('ix_reg_doc_language_code', table_name='reg_doc')
    op.drop_index(op.f('ix_reg_doc_code'), table_name='reg_doc')
    op.drop_table('reg_doc')
    # ### end Alembic commands ###
